### ISSUE TITLE
Tests failing in the version published in master.

### ISSUE THREAD

**Issue by danigomez** [szokodiakos/typegoose#22]
I'm getting this erros while running the test in master, it seems to be related to the last changes of plugins.

```
> typegoose@3.1.1 lint /home/dgomez/Proyectos/OpenSource/typegoose
> tslint --type-check --project tsconfig.json

Error at src/typegoose.ts:53:29: Property 'mongoosePlugin' does not exist on type 'string'.
Error at src/typegoose.ts:53:52: Property 'options' does not exist on type 'string'.
Error at src/typegoose.ts:59:19: Property 'get' does not exist on type 'string'.
Error at src/typegoose.ts:60:38: Property 'get' does not exist on type 'string'.
Error at src/typegoose.ts:62:19: Property 'set' does not exist on type 'string'.
Error at src/typegoose.ts:63:38: Property 'set' does not exist on type 'string'.

```

**Comment by rjmunro** [comment]
It happens at the linting stage - `npm run lint` will trigger it.

I'm getting the same even if I check out v3.1.0.

**Comment by rjmunro** [comment]
I have fixed the above in #25. In the process of figuring out the problem, I noticed that it doesn't work if you use typescript 2.2.1, as specified in package.json; it only works with 2.3.0 and above. I've added tests to detect this possibility and to fix package.json in #24.
