### ISSUE TITLE
@instanceMethod for subdocuments ?

### ISSUE THREAD

**Issue by MateuszKicinski** [szokodiakos/typegoose#209]
Hi, I ran into this issue while trying to use an @instanceMethod decorator for a subclass in one of mongo Documents. I have a class Rabbit that extends Typegoose, class Rabbit has a field carrot of type Carrot, like described below. 

``` 
export class Rabbit extends Typegoose{
    @prop({default: new Carrot()})
    carrot: Carrot;
}
```

Class carrot on the other hand has an @instanceMethod bite()

```
export class Carrot extends Typegoose {
    @instanceMethod
    public bite(this: InstanceType<Carrot>) {
        return 'bitten';
    }
}
```

When trying to run carrot.bite() I get this error:
`TypeError: carrot.bite is not a function`

Some guidance would be appreciated ;)

**Comment by JakeAi** [comment]
@MateuszKicinski you somewhat lack enough code to understand what you're wanting. You have `public current` in your Carrot class, instead of `public bite`
```TS
let model = new Carrot();
model.bite();
```
@instanceMethod
    public current() is not public bite()

**Comment by MateuszKicinski** [comment]
Sry I've mistaken the method name, I fixed it now

**Comment by MateuszKicinski** [comment]
It seems I've been doing it wrong by trying to use instance methods on plain classes and not InstanceType of plain classes. 

@JakeAi, the way you did it is simply having two objects in seperate documents. But I keep certain objects as fields in a document therefore I cannot reference the model directly because I simply do not have a model for a given class (like the Carrot class) I only have the parent object model (Rabbit) and I'm trying to get an InstanceType of that field in the parent class (rabbit.carrot) but it seems that InstanceTypes are created for documents only.

**Comment by cjanietz** [comment]
Typegoose is actually not creating instance methods for subdocuments. I have fixed it in my PR but it has not been merged #199

**Comment by singhsoldier13** [comment]
Is it working with Latest release? 5.5.1?

**Comment by MateuszKicinski** [comment]
@JulianMelzig sorry for the late response, I haven't use typegoose much since but at the time being I have created separate classes that took the original object in the constructor and then have some instance like methods run on them, for example:
 
```
export class Carrot extends Typegoose {
   bites: number;
}

export class CarrotPackage(){
    private carrot: Carrot;
    constructor(carrot: Carrot){
          this.carrot = carrot;
     }

     bite(){
           bites++;
           return 'bitten';
     }
}
```

**Comment by hasezoey** [comment]
this seems to be solved by #199, so i think its reasonable to be closed

@Ben305
